version: '3'
services:
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./db/docker-entrypoint-initdb.d/mozy.js:/docker-entrypoint-initdb.d/mozy.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  app:
    build: ./backend
    volumes:
      - ./:/srv/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: "/srv/backend"
