version: "3"
services:
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./db/docker-entrypoint-initdb.d/mozy.js:/docker-entrypoint-initdb.d/mozy.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db

  app:
    build: ./backend
    volumes:
      - ./:/srv/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: "/srv/backend"
    depends_on:
      - db
