# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900f067a538cb4dc09c66b11e3fdbfaca8f7872daa7382b68945e62f156836af46ebaa5085ff02eb1e329f2aa99575604c7ef4fb719be11542381432ad4e9074

test:
  secret_key_base: 87a93e600b57f1f616a1dfd9bf1347472f52bf23c8f5d02656c9a6382c905479f1d43242c9b141790d630bfd32fbf262a96b540de9845223811a92b756732480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
